CREATE TABLE IF NOT EXISTS member(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(256) NOT NULL UNIQUE,
    password VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS authority(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    authority VARCHAR(256),
    member_id BIGINT,
    FOREIGN KEY(member_id) REFERENCES member(id)
);

CREATE TABLE IF NOT EXISTS article(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(256)
);